name: Generate Antora UI with Gulp

on:
  push:
    branches:
        - main
    tags:
        - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm install

    - name: Generate Antora UI
      run: gulp bundle

    - name: Generates Pages
      run: gulp preview:build

    - name: Deploy Antora UI to GitHub Pages
      if: ${{ github.event_name != 'pull_request' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        
    - name: Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/ui-bundle.zip
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        generate_release_notes: true
        draft: false
        prerelease: false
